on:
  push
jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: echo ::add-matcher::.github/workflows/matcher.json
      - run: go test
